### PR TITLE
Violent Python

### PR DESCRIPTION
**Pull request by AlexandreProenca**
Violent Python shows you how to move from a theoretical understanding of offensive computing concepts to a practical implementation

### CODE REVIEW

**Comment by revolunet** [comment]
much interesting, thank you !
Except we only provide legal material and this website is not legal at all, so cant merge this...

**Comment by revolunet** [comment]
and infested with malware too

**Comment by AlexandreProenca** [comment]
Sorry, I no knew about this website, I will try found this content in legal website, thank you for replay.

**Comment by revolunet** [comment]
:

**Pull request closed without merging**
