### PR TITLE
Python Crash Course Book added

### PR DESCRIPTION
**Pull request by RafaelBroseghini**
Added Python Crash Course Book and its respective img.

### CODE REVIEW

**Comment by revolunet** [comment]
Hi,

Thanks for the submission; is this ebook available for free ? 

We only reference free ebooks, eventually with required registration

**Comment by RafaelBroseghini** [comment]
Yes. http://ap-n.us/books/Programming/Python%20Crash%20Course.pdf

**Comment by revolunet** [comment]
thanks. the `url` should point to the ebook directly please.

**Comment by revolunet** [comment]
url is 404 :)

**Pull request closed without merging**
