### PR TITLE
Add Filter

### PR DESCRIPTION
**Pull request by jeremejazz**
Adding filter as described in issue #30 .

### CODE REVIEW

**Comment by jeremejazz** [comment]
You can view the page [here](http://jeremejazz.github.io/PythonBooks).

**Comment by revolunet** [comment]
awesome, thanks man ! 👍

**Comment by revolunet** [comment]
and its online : http://pythonbooks.revolunet.com/

**Comment by jeremejazz** [comment]
wow thanks. glad to help :smile

**Pull request merged**
